version: '1'
services:
  fastp:
    image: biocontainers/fastp:v0.20.1_cv1
    volumes:
      - .:/data
    command: fastp -i data/output_MTHFR_1.fastq  -I data/output_MTHFR_2.fastq --out1 /data/output1.fastq --out2 /data/output2.fastq
    platform: linux/amd64

  bowtie2:
    image: biocontainers/bowtie2:v2.4.1_cv1
    depends_on:
      - fastp
    volumes:
      - .:/data
    command: bowtie2-build data/GCA_000001405.29_GRCh38.p14_genomic.fasta index_name && bowtie2 --no-unal -p 4 -x index_name -1 /data/output1.fastq -2 /data/output2.fastq -S /data/output.sam
    platform: linux/amd64

  samtools:
    image: biocontainers/samtools:v1.9-4-deb_cv1
    depends_on:
      - bowtie2
    volumes:
      - .:/data
    command: samtools view -bS /data/output.sam -o /data/sort_output.bam 
    platform: linux/amd64

  freebayes:
    image: biocontainers/freebayes:v1.2.0-2-deb_cv1
    depends_on:
      - samtools
    volumes:
      - .:/data
    command: sh -c "freebayes -f data/GCA_000001405.29_GRCh38.p14_genomic.fasta /data/sort_output.bam > /data/output.vcf"
    platform: linux/amd64
